name = "Ryan Gosling (Kinsa)"
description = "Accomplished actor, captivating with versatility and charisma."
keywords = "Ryan Gosling, actor, filmography, awards, versatile performances, Hollywood"
image = "ryanisliterallyme.jpg"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
gtag_id = "G-XLJ81DCZFV"
base_url = "https://thevahidal.github.io/jake"

[[sections]]
title = "Ryan Gosling Films"
description = "A collection of Ryan Gosling's finest films"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/watch?v=gCcx85zbxz4"
[[sections.items]]
title = "Blade Runner 2049"
description = "A visually stunning sci-fi sequel starring Ryan Gosling as Officer K"
url = "https://www.imdb.com/title/tt1856101/"
[[sections.items]]
title = "Drive"
description = "A neo-noir action thriller featuring Ryan Gosling as a skilled getaway driver"
url = "https://www.imdb.com/title/tt0780504/"
[[sections.items]]
title = "La La Land"
description = "A heartwarming musical romance starring Ryan Gosling and Emma Stone"
url = "https://www.imdb.com/title/tt3783958/"
[[sections.items]]
title = "The Nice Guys"
description = "A buddy-cop comedy with Ryan Gosling and Russell Crowe investigating a mysterious case"
url = "https://www.imdb.com/title/tt3799694/"



[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/ryangoslinguk/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/imdb/ffffff"
title = "IMDb"
url = "https://www.imdb.com/name/nm0331516/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Ryan_Gosling"
[[sections.items]]
title = "Rotten Tomatoes"
icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
url = "https://www.rottentomatoes.com/celebrity/ryan_gosling"
